type BookSource = 'BUY_NEW_OFFLINE'
    | 'BUY_NEW_ONLINE'
    | 'BUY_USED_OFFLINE'
    | 'BUY_USED_ONLINE'
    | 'LIBRARY'
    | 'BORROW_STORE'
    | 'BORROW_FRIENDS'
    | 'SUBSCRIPTION'
    | 'OTHERS'
    | 'NOT_PROVIDED'

type BookForm = 'PHYSICAL'
    | 'EBOOK'
    | 'AUDIO'

type BookLanguage = 'KOREAN'
    | 'ENGLISH'
    | 'JAPANESE'
    | 'CHINESE'
    | 'FRENCH'
    | 'SPANISH'
    | 'GERMAN'
    | 'ITALIAN'
    | 'UNKNOWN'

export type {BookSource, BookForm, BookLanguage}